### ISSUE TITLE
How did you train the pSp model?

### ISSUE THREAD

**Issue by t109598032** [xuduo35/StyleFlowPytorch#1]
Hello, thank you for providing this code! I have the question about the pSp model.
I have trained the pSp model by the [code](https://github.com/eladrich/pixel2style2pixel) you mentioned in readme. Then I load my trained pSp model in `encoder_init()` of `imageencoder.py`, it happened some problems:

1. dictionary key mismatch:
- the original pSp model you provided, when it loaded, I use `print(state_dict.keys())`, the dictionary key would be: `dict_keys(['encoder', 'dlatent_avg'])`

- the pSp model trained by myself would be: `dict_keys(['state_dict', 'opts', 'latent_avg'])`

2. then I found that 'encoder' and 'state_dict' are the same type of `<class 'collections.OrderedDict'>`, so I change `encoder.load_state_dict(state_dict['encoder'])` to `encoder.load_state_dict(state_dict['state_dict'])`, then it throw the error:
> Traceback (most recent call last):
>   File "gendata.py", line 71, in <module>
>     encoder, G, dlatent_avg = encoder_init(device)
>   File "/home/chenpu/StyleFlowPytorch/webui/imageencoder.py", line 105, in encoder_init
>     encoder.load_state_dict(state_dict['state_dict'])
>   File "/home/chenpu/anaconda3/envs/StyleFlow/lib/python3.7/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict
>     self.__class__.__name__, "\n\t".join(error_msgs)))
> RuntimeError: Error(s) in loading state_dict for GradualStyleEncoder:
> 	Missing key(s) in state_dict: "input_layer.0.weight", "input_layer.1.weight", "input_layer.1.bias", "input_layer.1.running_mean", "input_layer.1.running_var", "input_layer.2.weight", "body.0.res_layer.0.weight", "body.0.res_layer.0.bias", "body.0.res_layer.0.running_mean", "body.0.res_layer.0.running_var", "body.0.res_layer.1.weight", "body.0.res_layer.2.weight", "body.0.res_layer.3.weight", "body.0.res_layer.4.weight", "body.0.res_layer.4.bias", "body.0.res_layer.4.running_mean", "body.0.res_layer.4.running_var", "body.0.res_layer.5.fc1.weight", "body.0.res_layer.5.fc2.weight", "body.1.res_layer.0.weight", "body.1.res_layer.0.bias", "body.1.res_layer.0.running_mean", "body.1.res_layer.0.running_var", "body.1.res_layer.1.weight", "body.1.res_layer.2.weight", "body.1.res_layer.3.weight", "body.1.res_layer.4.weight", "body.1.res_layer.4.bias", "body.1.res_layer.4.running_mean", "body.1.res_layer.4.running_var", "body.1.res_layer.5.fc1.weight", "body.1.res_layer.5.fc2.weight", "body.2.res_layer.0.weight", "body.2.res_layer.0.bias", ...................
(etc.)

Do you have any ideas about it? I am wonder how did you train the pSp model. thank you very much!

**Comment by xuduo35** [comment]
I get the encoder from psp, just using the pretrained weights and below code.

`torch.save({
     'encoder': net.encoder.state_dict(),
      'dlatent_avg': net.latent_avg
 }, './psp_encoder.pth')`
