### ISSUE TITLE
A question about parsing attributes in `gendata.py`

### ISSUE THREAD

**Issue by CIntellifusion** [xuduo35/StyleFlowPytorch#10]
As shown in the below picture, the expression line is assigned with values of glasses. 
I am confused and wonder whether it is a bug or intended?
Thanks for your reply 
![bdb1a27fca984154cfc130386a6c662](https://github.com/xuduo35/StyleFlowPytorch/assets/96377955/7ec1238d-ff5d-4de8-b745-be47b7a984a6)

And I am not sure if it causes problems in  #[issue2](https://github.com/xuduo35/StyleFlowPytorch/issues/2)

**Comment by xuduo35** [comment]
Seems so. You can fix it locally or give me a PR.

**Comment by CIntellifusion** [comment]
> Seems so. You can fix it locally or give me a PR.

Thanks for early reply
I am glad to PR after confirming my local modification works correctly
