### ISSUE TITLE
question about input custom face with glasses

### ISSUE THREAD

**Issue by yjmpepe** [xuduo35/StyleFlowPytorch#2]
1、I try to input custom face with glasses, the glasses attribution is still 0 when applying gendata.py. 
2、I set the glasses attibution to 1 manually in gendata.py.
3、The glasses cannot be removed when applying app.py.
4、But the random latents manipulation with glasses are correct.

**Comment by xuduo35** [comment]
The glasses detection is using project 'https://github.com/foamliu/Face-Attributes-Mobile'. You can add some debug info in gendata.py to check if its output is right or not. But it won't affect latents manipulation, it only assign the initial value for your image. You can try other face image. How about other attributes?

**Comment by yjmpepe** [comment]
Thanks for your kindly reply!

well operated random generated pics:
1、find random generated pics with glasses when running app.py(fig. 1)
2、u can see the glasses scrollbar is init as 1
3、set the glasses scrollbar to 0,  and the glasses can be removed(fig. 2)

failed operation:
1、prepare some face pics with glasses as input(fig. 3)
2、manually fix the glasses attribute to 1 during running gendata.py(fig. 4-5)
3、the glasses scrollbar is then init as 1 when running app.py ./data(fig. 6)
4、set the glasses scrollbar to 0, but the glasses cannot be removed(fig. 7-9)

i know the glasses detection operation won't affect latents manipulation, it only assign the initial value. But  why the custom face with glasses failed? Is there some mistakes in  app.py ./data?

![1](https://user-images.githubusercontent.com/51482722/152675039-4dbe75b0-1c93-4b75-a80e-b4d3e1aa6d0e.png)
![2](https://user-images.githubusercontent.com/51482722/152675042-438f995c-1524-4dc5-9b84-b4312b5b9e8e.png)
![3](https://user-images.githubusercontent.com/51482722/152675044-c0cf4dfe-9d7f-4ff8-b3b3-c8a3196f0b91.png)
![4](https://user-images.githubusercontent.com/51482722/152675045-39349fb2-8434-4172-8d42-53049ef93cce.png)
![5](https://user-images.githubusercontent.com/51482722/152675046-98f09793-df73-4609-b135-e90c1684ec72.png)
![6](https://user-images.githubusercontent.com/51482722/152675047-57420486-70e2-453c-91a3-38e018a09369.png)
![7](https://user-images.githubusercontent.com/51482722/152675049-2d54dcda-b211-4594-a23d-ce22b842cdf4.png)
![8](https://user-images.githubusercontent.com/51482722/152675050-c22b889b-c64e-41ea-b6bb-c771f27afafb.png)
![9](https://user-images.githubusercontent.com/51482722/152675035-c92ee459-48a9-4a87-864f-9374fb33967d.png)

**Comment by xuduo35** [comment]
Maybe it's due to encoder, you can use e4e encoder(https://github.com/omertov/encoder4editing). e4e can generate latent more editable, many papers use it for experiment.

**Comment by yjmpepe** [comment]
I think it's the reason, thanks, i'll try e4e.
