### ISSUE TITLE
Running 512px Models

### ISSUE THREAD

**Issue by uie37930** [xuduo35/StyleFlowPytorch#3]
Hi xuduo35. Thanks a lot for your great work! Since I am on a newer GPU (GTX3070) i was struggeling to get the tf styleflow version up and running so your version really saved my day. I was trying to use custom stylgan2 tf models with your code. I used adriansahlman's code to convert them into pytorch and replaced the Gs_ffhq.pth in the mymodels folder which worked flawless for 1024px models. However, whenever I try to do the same with 512px models, i get the following error in line 985 of stylegan2/models.py:
"AssertionError: Input mismatch, expected latents of shape (batch_size, 16, latent_size) but got (1, 18, 512)"
Do you have any idea how to solve this?

**Comment by xuduo35** [comment]
512px stylegan use different latent size. you can use adriansahlman's code to train a normal stylegan on any dataset and print some intermediate latent size result to check.
