### ISSUE TITLE
TypeError: tensor is not a torch image.

### ISSUE THREAD

**Issue by dqyyds** [xuduo35/StyleFlowPytorch#4]
thank you for your amazing work. But I met a little problem. when I run  python3 gendata.py ./images, I got this
Traceback (most recent call last):
  File "gendata.py", line 100, in <module>
    device, G, encoder, dlatent_avg, faceimg, truncation_psi=0.5, num_steps=1
  File "/home/ubuntu/extend/dq/StyleFlowPytorch-main/webui/imageencoder.py", line 63, in encode_real_images
    images = torchvision.transforms.Normalize(mean=0.5,std=0.5)(images/255.)
  File "/home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 175, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 209, in normalize
    raise TypeError('tensor is not a torch image.')
TypeError: tensor is not a torch image.
Could you tell me how to solve it. thanks a lot

**Comment by xuduo35** [comment]
Seems impossible.  torch.Tensor(images).to(device) will turn images from numpy to torch tensor. You can add print(images) to check it after torch.Tensor.
    images = torch.Tensor(images).to(device)
    images = torchvision.transforms.Normalize(mean=0.5,std=0.5)(images/255.)

**Comment by dqyyds** [comment]
> 

thanks for your reply. Could you tell me your Pytorch and cuda's version?

**Comment by xuduo35** [comment]
RTX3090
NVIDIA-SMI 470.63.01    Driver Version: 470.63.01    CUDA Version: 11.4 
efficientnet-pytorch==0.7.1
pytorch-lightning==1.5.10
torch==1.9.0+cu111
torchaudio==0.9.0
torchcontrib==0.0.2
torchdiffeq==0.2.2
torchfile==0.1.0
torchmetrics==0.7.3
torchnet==0.0.4
torchvision==0.10.0+cu111
