### ISSUE TITLE
有关validate的问题

### ISSUE THREAD

**Issue by Donkdot** [xuduo35/StyleFlowPytorch#9]
您好，有一个问题想请教您！我现在想对styleflow的relighting方法进行定量分析和我的方法对比，该如何在代码里进行呢？

**Comment by xuduo35** [comment]
具体什么问题，你要拿到什么信息。

**Comment by Donkdot** [comment]
感谢您回复！我的论文是relight方向的，审稿人想要我在实验部分加入和styleflow的relight部分的对比。这是他的审稿意见：
I think StyleFlow[1] is one of strong baselines that is capable of performing relighting based on SH coeff or a reference image (w.GAN inversion), but there is no comparison to [1].
我现在就是需要得到根据我输入的SH coeff和Reference image两种方法在styleflow中的结果，并且需要计算relighting之后的图片和原图的对比，然后计算MSE，LPIPS等指标，我需要在您的代码中哪些部分进行操作才能得到呢？
非常感谢您！

**Comment by xuduo35** [comment]
这个项目有点久了，你可以参考webui/gendata.py，他说的w.GAN inversion，是下面这个代码

        # encode image 
        dlatents = encode_real_images(
            device, G, encoder, dlatent_avg, faceimg, truncation_psi=0.5, num_steps=1
            )

这个文件里用DPR提取了光照信息。剩下的逻辑就在app.py里了，我建议你本地跑一下跟踪一下代码逻辑。看下我的README.md吧

**Comment by Donkdot** [comment]
好的 非常感谢！
